In [28]:
import yfinance as yf
from datetime import datetime, timedelta
import requests
from bs4 import BeautifulSoup
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
#Set-up end range

yesterday = datetime.now() - timedelta(1)
Last_Week = datetime.now() - timedelta(3)

exclude_weekend = [6,7]
weekdays  = [5,6]
date_range = []

for days in exclude_weekend:
    
    if days == datetime.isoweekday(yesterday):
    
        Reporting_Date = Last_Week
    
    else:
    
        Reporting_Date = yesterday
    
    Year = datetime.strftime(Reporting_Date, '%Y')
    Month = datetime.strftime(Reporting_Date, '%m')
    Day = datetime.strftime(Reporting_Date, '%d')

date= Year +'-'+ Month + '-' + Day

#set-up start range

master_start_date = Reporting_Date - timedelta(180)

year_start = datetime.strftime(master_start_date, '%Y')
month_start = datetime.strftime(master_start_date, '%m')
day_start = datetime.strftime(master_start_date, '%d')

start_date = year_start +'-'+ month_start +'-'+ day_start

print(date, start_date)

2024-06-19 2023-12-22


In [30]:
tickers = ['DAX',
          'SAP.DE',
          'SIE.DE',
          'ALV.DE',
          'AIR.DE',
          'DTE.DE',
          'MBG.DE',
          'BAS.DE',
          'IFX.DE',
          'DHL.DE',
          'ADS.DE']

In [31]:
prices = yf.download(tickers,  # list of tickers
            period = "1y",         # time period
            interval = "1d",       # trading interval
            prepost = False,       # download pre/post market hours data?
            repair = True)  

[**********************55%*                      ]  6 of 11 completedSIE.DE: fixed 1/1 value=0 errors in 1d price data: [Timestamp('2023-10-06 00:00:00+0200', tz='Europe/Berlin')]
[**********************64%******                 ]  7 of 11 completedDTE.DE: fixed 2/2 value=0 errors in 1d price data: [Timestamp('2023-06-27 00:00:00+0200', tz='Europe/Berlin'), Timestamp('2023-07-20 00:00:00+0200', tz='Europe/Berlin')]
[**********************73%**********             ]  8 of 11 completedDHL.DE: fixed 18/18 value=0 errors in 1d price data
[**********************82%**************         ]  9 of 11 completedIFX.DE: fixed 3/3 value=0 errors in 1h price data: [Timestamp('2024-06-17 09:00:00+0200', tz='Europe/Berlin'), Timestamp('2024-06-18 09:00:00+0200', tz='Europe/Berlin'), Timestamp('2024-06-19 09:00:00+0200', tz='Europe/Berlin')]
IFX.DE: fixed 1/1 value=0 errors in 1d price data: [Timestamp('2024-06-19 00:00:00+0200', tz='Europe/Berlin')]
[*********************100%***********************] 

In [56]:
prices['Adj Close']

ADS.DE      AIR.DE      ALV.DE     BAS.DE        DAX  \
Date                                                                   
2023-06-20  168.924988  131.272964  198.653122  39.810776  29.604893   
2023-06-21  176.142960  129.026779  198.320847  39.773445  29.400183   
2023-06-22  180.828690  126.800453  197.893631  39.549446  29.380686   
2023-06-23  176.342377  125.945709  198.558182  39.418781  28.942022   
2023-06-26  176.043274  126.919716  198.605652  39.932110  28.922527   
...                ...         ...         ...        ...        ...   
2024-06-14  224.899994  143.800003  253.399994  44.584999  32.064999   
2024-06-17  219.100006  145.779999  255.600006  44.840000  32.310001   
2024-06-18  216.000000  145.779999  257.000000  45.040001  32.360001   
2024-06-19  215.000000  147.960007  258.100006  44.945000        NaN   
2024-06-20  216.300003  148.039993  258.799988  45.375000        NaN   

               DHL.DE     DTE.DE     IFX.DE     MBG.DE      SAP.DE      SIE.DE  
Date                                                                            
2023-06-20  41.992912  18.586411  36.955059  69.623474  123.023636  157.048660  
2023-06-21  40.901134  18.580614  36.579079  68.695778  121.463371  155.940216  
2023-06-22  41.311150  18.771868  36.742332  67.118690  121.562126  156.076340  
2023-06-23  41.182423  18.891644  35.327457  66.821831  121.048622  152.634338  
2023-06-26  41.001255  19.024940  35.485764  66.775452  120.100616  151.175858  
...               ...        ...        ...        ...         ...         ...  
2024-06-14  37.750000  22.629999  36.500000  63.200001  174.779999  165.740005  
2024-06-17  37.660000  22.570000  36.150002  63.590000  175.759995  168.100006  
2024-06-18  37.970001  22.570000  35.985001  63.520000  176.000000  168.440002  
2024-06-19  37.759998  22.889999  34.689999  63.830002  176.279999  168.240005  
2024-06-20  38.139999  22.790001  34.959999  64.059998  177.460007  170.119995  

[260 rows x 11 columns]

In [59]:
bars_data = {}

for stock in tickers:
    bars_data[stock] = np.array([prices[('Open', stock)].values, prices[('High', stock)].values, prices[('Low', stock)].values, prices[('Adj Close', stock)].values]).T

In [60]:
bars_data

{'DAX': array([[30.5       , 30.54999924, 30.17000008, 29.60489273],
        [30.05999947, 30.4640007 , 30.05999947, 29.40018272],
        [29.97999954, 30.25      , 29.62000084, 29.38068581],
        ...,
        [32.34999847, 32.40999985, 32.15999985, 32.36000061],
        [        nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan]]),
 'SAP.DE': array([[125.30000305, 125.66000366, 124.27999878, 123.02363586],
        [124.01999664, 124.41999817, 122.77999878, 121.46337128],
        [122.77999878, 123.23999786, 121.37999725, 121.56212616],
        ...,
        [176.5       , 177.16000366, 174.75999451, 176.        ],
        [175.6000061 , 176.38000488, 174.69999695, 176.27999878],
        [177.03999329, 178.22000122, 177.03999329, 177.46000671]]),
 'SIE.DE': array([[162.94000244, 162.96000671, 161.5       , 157.04866028],
        [161.72000122, 162.80000305, 159.75999451, 155.94021606],
        [158.        , 160.52000427, 157.47

In [61]:
index = 'DAX'

holdings = [
    'SAP.DE',
    'SIE.DE',
    'ALV.DE',
    'AIR.DE',
    'DTE.DE',
    'MBG.DE',
    'BAS.DE',
    'IFX.DE',
    'DHL.DE',
    'ADS.DE'
]

In [62]:
corr_data = {}
stock_ret_store = {}

df_data = bars_data[index]
reshape_df = df_data.reshape(-1, 4)
index_ret = np.log(reshape_df[1:, :]/reshape_df[:-1, :])

In [63]:
test = bars_data[index]
print(test)

[[30.5        30.54999924 30.17000008 29.60489273]
 [30.05999947 30.4640007  30.05999947 29.40018272]
 [29.97999954 30.25       29.62000084 29.38068581]
 ...
 [32.34999847 32.40999985 32.15999985 32.36000061]
 [        nan         nan         nan         nan]
 [        nan         nan         nan         nan]]


In [64]:
for stock in holdings:
    df_data = bars_data[stock]
    reshape_df = df_data.reshape(-1, 4)
    stock_ret = np.log(reshape_df[1:, :]/reshape_df[:-1, :])
    stock_ret_store[stock] = stock_ret
    
    corr_data[stock] = np.corrcoef(index_ret, stock_ret)

In [65]:
corr_data

{'SAP.DE': array([[ 1.        , -0.58489214,  0.76578422, ..., -0.89248818,
          0.37090766,  0.56890497],
        [-0.58489214,  1.        , -0.84465243, ...,  0.88255922,
         -0.05401227, -0.99229454],
        [ 0.76578422, -0.84465243,  1.        , ..., -0.93287961,
          0.56432673,  0.78201097],
        ...,
        [-0.89248818,  0.88255922, -0.93287961, ...,  1.        ,
         -0.31122224, -0.85975984],
        [ 0.37090766, -0.05401227,  0.56432673, ..., -0.31122224,
          1.        , -0.06392913],
        [ 0.56890497, -0.99229454,  0.78201097, ..., -0.85975984,
         -0.06392913,  1.        ]]),
 'SIE.DE': array([[ 1.        , -0.58489214,  0.76578422, ..., -0.66373083,
          0.36201533,  0.78326102],
        [-0.58489214,  1.        , -0.84465243, ...,  0.2160073 ,
         -0.79196845, -0.12109748],
        [ 0.76578422, -0.84465243,  1.        , ..., -0.70386492,
          0.87667007,  0.58963587],
        ...,
        [-0.66373083,  0.2160073 ,

In [ ]:
realized_estimate = {}

for stock in filtered_list:
    df_data = bars_data[stock]
    reshape_df = df_data.reshape

In [26]:
bars_data


{'DAX': array([[[171.11999512, 172.44000244, 168.94000244, 168.92498779],
         [172.1000061 , 177.44000244, 171.63999939, 176.14295959],
         [175.05999756, 181.77999878, 174.5       , 180.82868958],
         ...,
         [221.19999695, 222.19999695, 214.8999939 , 216.        ],
         [215.8999939 , 216.1000061 , 214.30000305, 215.        ],
         [215.5       , 215.6000061 , 214.30000305, 215.5       ]],
 
        [[131.53999329, 132.63999939, 130.77999878, 131.27296448],
         [132.46000671, 133.17999268, 129.44000244, 129.02677917],
         [128.77999878, 129.38000488, 126.87999725, 126.80045319],
         ...,
         [145.77999878, 145.77999878, 145.77999878, 145.77999878],
         [148.46000671, 148.69999695, 147.63999939, 147.96000671],
         [148.36000061, 148.88000488, 148.19999695, 148.47999573]],
 
        [[209.6000061 , 210.44999695, 209.1000061 , 198.65312195],
         [209.05000305, 210.44999695, 208.6499939 , 198.32084656],
         [207.8000030